version: '3.9'

services:
  wordpress:
    build:
      context: ./build
      args:
        PUID: 1000
        PGID: 1000
    container_name: wordpress-booking
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - traefik
      - wp_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-booking.rule=Host(`booking.local`)"
      - "traefik.http.routers.wordpress-booking.entrypoints=web"
      - "traefik.http.services.wordpress-booking.loadbalancer.server.port=80"

  db:
    image: mysql:8.0
    container_name: wordpress-booking-db
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net

networks:
  traefik:
    external: true
  wp_net:
    driver: bridge

volumes:
  db_data:
